name: Build com Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Docker Buildx (para build multi-plataforma)
      uses: docker/setup-buildx-action@v3

    - name: Build e subir containers com Docker Compose
      working-directory: study_project/project_6/DesafioWexDockerCompose
      run: docker compose up --build -d

    - name: Verificar containers ativos
      run: docker ps
