# Etapa 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia somente o projeto JarbasBot
COPY ./DesafioWEXDockerCompose/JarbasBot ./JarbasBot

# Vai para o diretório do projeto
WORKDIR /src/JarbasBot

# Restaura as dependências
RUN dotnet restore

# Publica o app em modo Release
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copia os arquivos publicados da etapa anterior
COPY --from=build /app/publish .

# Define a porta da aplicação
ENV ASPNETCORE_URLS=http://+:80

# Executa o JarbasBot
ENTRYPOINT ["dotnet", "JarbasBot.dll"]